language: ruby
cache: bundler

rvm:  
  - 2.1.2

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - my@email.com
    on_failure: change
    on_success: never
env:
  - CODECLIMATE_REPO_TOKEN=7bddc45388d2b42ac29153b0539f60836f5bc3acf7dd0b93dfa3bd8e4f2adcbc 